### ISSUE TITLE
how the example works?

### ISSUE THREAD

**Issue by gedw99** [RussellLuo/dbtest#1]
this is not generated but is the contract that is used for the code gen?

**Comment by RussellLuo** [comment]
> this is not generated but is the contract that is used for the code gen?

@gedw99 Yes, you are right! See the example [README](https://github.com/RussellLuo/dbtest/tree/master/examples#readme) please.

**Comment by gedw99** [comment]
thanks @RussellLuo 

Quite cool architecture. I like its annotations approach and a schema based approach to testing.

Do you have any thoughts on things you want to add and what you want this to evolve as ?

**Comment by RussellLuo** [comment]
- Short-term goal: continuously improve the support for SQL databases.
- Long-term goal: possibly add support for NoSQL databases (e.g. Redis or MongoDB).
